const mainFunctions = require("./main");

module.exports = {
  // main Database
  createTask: mainFunctions.createTask,
  getIdListOfTaskByField: mainFunctions.getIdListOfTaskByField,
  getTaskById: mainFunctions.getTaskById,
  getTaskAggById: mainFunctions.getTaskAggById,
  getTaskListByQuery: mainFunctions.getTaskListByQuery,
  getTaskStatsByQuery: mainFunctions.getTaskStatsByQuery,
  getTaskByQuery: mainFunctions.getTaskByQuery,
  updateTaskById: mainFunctions.updateTaskById,
  updateTaskByIdList: mainFunctions.updateTaskByIdList,
  updateTaskByQuery: mainFunctions.updateTaskByQuery,
  deleteTaskById: mainFunctions.deleteTaskById,
  deleteTaskByQuery: mainFunctions.deleteTaskByQuery,
  dbScriptCreateTask: mainFunctions.dbScriptCreateTask,
  dbScriptUpdateTask: mainFunctions.dbScriptUpdateTask,
  dbScriptDeleteTask: mainFunctions.dbScriptDeleteTask,
  dbScriptGetTask: mainFunctions.dbScriptGetTask,
  dbScriptListTasks: mainFunctions.dbScriptListTasks,
  createNewtasktotest: mainFunctions.createNewtasktotest,
  getIdListOfNewtasktotestByField:
    mainFunctions.getIdListOfNewtasktotestByField,
  getNewtasktotestById: mainFunctions.getNewtasktotestById,
  getNewtasktotestAggById: mainFunctions.getNewtasktotestAggById,
  getNewtasktotestListByQuery: mainFunctions.getNewtasktotestListByQuery,
  getNewtasktotestStatsByQuery: mainFunctions.getNewtasktotestStatsByQuery,
  getNewtasktotestByQuery: mainFunctions.getNewtasktotestByQuery,
  updateNewtasktotestById: mainFunctions.updateNewtasktotestById,
  updateNewtasktotestByIdList: mainFunctions.updateNewtasktotestByIdList,
  updateNewtasktotestByQuery: mainFunctions.updateNewtasktotestByQuery,
  deleteNewtasktotestById: mainFunctions.deleteNewtasktotestById,
  deleteNewtasktotestByQuery: mainFunctions.deleteNewtasktotestByQuery,

  createRfewtgwre: mainFunctions.createRfewtgwre,
  getIdListOfRfewtgwreByField: mainFunctions.getIdListOfRfewtgwreByField,
  getRfewtgwreById: mainFunctions.getRfewtgwreById,
  getRfewtgwreAggById: mainFunctions.getRfewtgwreAggById,
  getRfewtgwreListByQuery: mainFunctions.getRfewtgwreListByQuery,
  getRfewtgwreStatsByQuery: mainFunctions.getRfewtgwreStatsByQuery,
  getRfewtgwreByQuery: mainFunctions.getRfewtgwreByQuery,
  updateRfewtgwreById: mainFunctions.updateRfewtgwreById,
  updateRfewtgwreByIdList: mainFunctions.updateRfewtgwreByIdList,
  updateRfewtgwreByQuery: mainFunctions.updateRfewtgwreByQuery,
  deleteRfewtgwreById: mainFunctions.deleteRfewtgwreById,
  deleteRfewtgwreByQuery: mainFunctions.deleteRfewtgwreByQuery,

  createTrewytgre: mainFunctions.createTrewytgre,
  getIdListOfTrewytgreByField: mainFunctions.getIdListOfTrewytgreByField,
  getTrewytgreById: mainFunctions.getTrewytgreById,
  getTrewytgreAggById: mainFunctions.getTrewytgreAggById,
  getTrewytgreListByQuery: mainFunctions.getTrewytgreListByQuery,
  getTrewytgreStatsByQuery: mainFunctions.getTrewytgreStatsByQuery,
  getTrewytgreByQuery: mainFunctions.getTrewytgreByQuery,
  updateTrewytgreById: mainFunctions.updateTrewytgreById,
  updateTrewytgreByIdList: mainFunctions.updateTrewytgreByIdList,
  updateTrewytgreByQuery: mainFunctions.updateTrewytgreByQuery,
  deleteTrewytgreById: mainFunctions.deleteTrewytgreById,
  deleteTrewytgreByQuery: mainFunctions.deleteTrewytgreByQuery,
};
