const mainFunctions = require("./main");

module.exports = {
  // main Database
  createTask: mainFunctions.createTask,
  getIdListOfTaskByField: mainFunctions.getIdListOfTaskByField,
  getTaskById: mainFunctions.getTaskById,
  getTaskAggById: mainFunctions.getTaskAggById,
  getTaskListByQuery: mainFunctions.getTaskListByQuery,
  getTaskStatsByQuery: mainFunctions.getTaskStatsByQuery,
  getTaskByQuery: mainFunctions.getTaskByQuery,
  updateTaskById: mainFunctions.updateTaskById,
  updateTaskByIdList: mainFunctions.updateTaskByIdList,
  updateTaskByQuery: mainFunctions.updateTaskByQuery,
  deleteTaskById: mainFunctions.deleteTaskById,
  deleteTaskByQuery: mainFunctions.deleteTaskByQuery,
  dbScriptCreateTask: mainFunctions.dbScriptCreateTask,
  dbScriptUpdateTask: mainFunctions.dbScriptUpdateTask,
  dbScriptDeleteTask: mainFunctions.dbScriptDeleteTask,
  dbScriptGetTask: mainFunctions.dbScriptGetTask,
  dbScriptListTasks: mainFunctions.dbScriptListTasks,
  createNewtasktotest: mainFunctions.createNewtasktotest,
  getIdListOfNewtasktotestByField:
    mainFunctions.getIdListOfNewtasktotestByField,
  getNewtasktotestById: mainFunctions.getNewtasktotestById,
  getNewtasktotestAggById: mainFunctions.getNewtasktotestAggById,
  getNewtasktotestListByQuery: mainFunctions.getNewtasktotestListByQuery,
  getNewtasktotestStatsByQuery: mainFunctions.getNewtasktotestStatsByQuery,
  getNewtasktotestByQuery: mainFunctions.getNewtasktotestByQuery,
  updateNewtasktotestById: mainFunctions.updateNewtasktotestById,
  updateNewtasktotestByIdList: mainFunctions.updateNewtasktotestByIdList,
  updateNewtasktotestByQuery: mainFunctions.updateNewtasktotestByQuery,
  deleteNewtasktotestById: mainFunctions.deleteNewtasktotestById,
  deleteNewtasktotestByQuery: mainFunctions.deleteNewtasktotestByQuery,
};
